"""
Haq — Tier-3 PDF Service
Receives { scheme_id, template, profile } from the n8n Executor and returns a
polished, branded, pre-filled government-style application form as a PDF.

Run:  python3 app.py    (listens on :3200, endpoint POST /fill)
"""
import io
from datetime import datetime

from flask import Flask, request, send_file, jsonify
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.pdfgen import canvas

app = Flask(__name__)

# ---- Branding palette -------------------------------------------------------
SAFFRON = colors.HexColor("#FF6B1A")
INK     = colors.HexColor("#1A1A2E")
GREY    = colors.HexColor("#6B7280")
LINE    = colors.HexColor("#D1D5DB")
GREEN   = colors.HexColor("#138808")

# ---- Scheme display metadata (extend as you add schemes) --------------------
SCHEME_META = {
    "rj_widow_pension": {
        "title_en": "Widow Pension Scheme",
        "title_hi": "विधवा पेंशन योजना",
        "dept": "Department of Social Justice & Empowerment, Govt. of Rajasthan",
        "form_no": "SJE / PEN / WID-2024",
    },
    "rj_old_age_pension": {
        "title_en": "Old Age Pension Scheme",
        "title_hi": "वृद्धावस्था पेंशन योजना",
        "dept": "Department of Social Justice & Empowerment, Govt. of Rajasthan",
        "form_no": "SJE / PEN / OAP-2024",
    },
    "pm_ujjwala": {
        "title_en": "PM Ujjwala Yojana (LPG Connection)",
        "title_hi": "पीएम उज्ज्वला योजना",
        "dept": "Ministry of Petroleum & Natural Gas, Govt. of India",
        "form_no": "MOPNG / UJJ / 2024",
    },
}

FIELD_LABELS = [
    ("name",            "Applicant Name"),
    ("age",             "Age"),
    ("gender",          "Gender"),
    ("marital_status",  "Marital Status"),
    ("category",        "Category (GEN/OBC/SC/ST)"),
    ("annual_income",   "Annual Income (INR)"),
    ("district",        "District"),
    ("state",           "State"),
    ("occupation",      "Occupation"),
    ("aadhaar_last4",   "Aadhaar (last 4 digits)"),
]


def _val(profile, key):
    v = profile.get(key)
    if v is None or v == "":
        return ""
    if key == "aadhaar_last4":
        return "XXXX-XXXX-" + str(v)
    if key == "annual_income":
        try:
            return "Rs. {:,}".format(int(v))
        except Exception:
            return str(v)
    return str(v)


def build_pdf(scheme_id, profile):
    meta = SCHEME_META.get(scheme_id, {
        "title_en": scheme_id, "title_hi": "",
        "dept": "Government of India", "form_no": "—",
    })
    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    W, H = A4

    # ---- Header band --------------------------------------------------------
    c.setFillColor(SAFFRON)
    c.rect(0, H - 38 * mm, W, 38 * mm, fill=1, stroke=0)
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 22)
    c.drawString(20 * mm, H - 20 * mm, "Application Form")
    c.setFont("Helvetica", 11)
    c.drawString(20 * mm, H - 27 * mm, meta["title_en"])
    c.setFont("Helvetica-Bold", 11)
    c.drawString(20 * mm, H - 33 * mm, meta["dept"])

    # Emblem placeholder (right)
    c.setStrokeColor(colors.white)
    c.setLineWidth(1.2)
    c.circle(W - 28 * mm, H - 19 * mm, 9 * mm, stroke=1, fill=0)
    c.setFont("Helvetica-Bold", 7)
    c.drawCentredString(W - 28 * mm, H - 20 * mm, "GOVT")

    # ---- Sub header / meta --------------------------------------------------
    y = H - 48 * mm
    c.setFillColor(GREY)
    c.setFont("Helvetica", 9)
    c.drawString(20 * mm, y, f"Form No: {meta['form_no']}")
    c.drawRightString(W - 20 * mm, y, "Generated by Haq (हक़) — " +
                      datetime.now().strftime("%d %b %Y, %H:%M"))
    c.setStrokeColor(LINE)
    c.setLineWidth(0.8)
    c.line(20 * mm, y - 3 * mm, W - 20 * mm, y - 3 * mm)

    # ---- Section: Applicant details ----------------------------------------
    y -= 14 * mm
    c.setFillColor(INK)
    c.setFont("Helvetica-Bold", 13)
    c.drawString(20 * mm, y, "1.  Applicant Details")
    y -= 4 * mm
    c.setStrokeColor(SAFFRON)
    c.setLineWidth(2)
    c.line(20 * mm, y, 60 * mm, y)

    y -= 10 * mm
    row_h = 11 * mm
    label_x, val_x = 24 * mm, 95 * mm
    for key, label in FIELD_LABELS:
        c.setFillColor(GREY)
        c.setFont("Helvetica", 10)
        c.drawString(label_x, y, label)
        c.setFillColor(INK)
        c.setFont("Helvetica-Bold", 11)
        val = _val(profile, key)
        c.drawString(val_x, y, val if val else "")
        # underline for the value field
        c.setStrokeColor(LINE)
        c.setLineWidth(0.6)
        c.line(val_x, y - 2 * mm, W - 24 * mm, y - 2 * mm)
        y -= row_h

    # ---- Section: Declaration ----------------------------------------------
    y -= 4 * mm
    c.setFillColor(INK)
    c.setFont("Helvetica-Bold", 13)
    c.drawString(20 * mm, y, "2.  Declaration")
    y -= 4 * mm
    c.setStrokeColor(SAFFRON)
    c.setLineWidth(2)
    c.line(20 * mm, y, 60 * mm, y)
    y -= 9 * mm
    c.setFillColor(GREY)
    c.setFont("Helvetica", 9.5)
    decl = ("I hereby declare that the information furnished above is true and correct "
            "to the best of my knowledge. I understand that any false statement may "
            "result in rejection of this application.")
    # simple wrap
    words, line = decl.split(), ""
    for w in words:
        if c.stringWidth(line + " " + w, "Helvetica", 9.5) < (W - 48 * mm):
            line = (line + " " + w).strip()
        else:
            c.drawString(24 * mm, y, line); y -= 5 * mm; line = w
    if line:
        c.drawString(24 * mm, y, line); y -= 5 * mm

    # ---- Signature blocks ---------------------------------------------------
    y -= 16 * mm
    c.setStrokeColor(INK)
    c.setLineWidth(0.8)
    c.line(24 * mm, y, 74 * mm, y)
    c.line(W - 74 * mm, y, W - 24 * mm, y)
    c.setFillColor(GREY)
    c.setFont("Helvetica", 9)
    c.drawString(24 * mm, y - 5 * mm, "Signature / Thumb impression")
    c.drawString(W - 74 * mm, y - 5 * mm, "Date & Place")

    # ---- Footer -------------------------------------------------------------
    c.setFillColor(GREEN)
    c.rect(0, 0, W, 10 * mm, fill=1, stroke=0)
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 8)
    c.drawCentredString(W / 2, 3.4 * mm,
        "This form was auto-prepared by Haq. Print, sign, and submit at your nearest office. "
        "Haq never charges citizens.")

    c.showPage()
    c.save()
    buf.seek(0)
    return buf


@app.route("/fill", methods=["POST"])
def fill():
    data = request.get_json(force=True, silent=True) or {}
    scheme_id = data.get("scheme_id", "unknown")
    profile = data.get("profile") or {}
    if isinstance(profile, str):
        import json
        try:
            profile = json.loads(profile)
        except Exception:
            profile = {}
    try:
        pdf = build_pdf(scheme_id, profile)
        fname = f"Haq_{scheme_id}_form.pdf"
        return send_file(pdf, mimetype="application/pdf",
                         as_attachment=True, download_name=fname)
    except Exception as e:
        return jsonify({"error": str(e)}), 500


@app.route("/health", methods=["GET"])
def health():
    return jsonify({"ok": True, "service": "haq-pdf", "schemes": list(SCHEME_META)})


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=3200)
